/* Palette generated by Material Palette - materialpalette.com/cyan/lime */

export const DARK_PRIMARY_COLOR = '#00b1b3'
export const DEFAULT_PRIMARY_COLOR = '#00bcd4'
export const LIGHT_PRIMARY_COLOR = '#B2EBF2'
export const TEXT_PRIMARY_COLOR = '#FFFFFF'
export const ACCENT_COLOR = '#45c289'
export const PRIMARY_TEXT_COLOR = '#212121'
export const SECONDARY_TEXT_COLOR = '#757575'
export const DIVIDER_COLOR = '#EEEEEE'
export const DRAWER_WIDTH = 298
export const HEADER_HEIGHT = 64
export const ERROR_COLOR = '#ff1744'
export const MAX_WIDTH = 900
